# **NLP: FINAL PROJECT**

* 1. import all the required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

* now fetch the csv file

In [2]:
df=pd.read_csv("train.txt", sep=';', header=None, names=['text', 'emotion'])
'''
read the csv file
use comma separator
to avoid our first value to become header, we used 'none'
i have given header column names values manually
'''

df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

* since machie learning can only deal with numbers so i have to replace the string data of emotion into numbers

In [3]:
# check for null values
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [4]:
# check the unique values of emotion
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [5]:
# now make a dictionary of all this emotions and number them
unique_emotions=df['emotion'].unique() # this will create an array and i will save this into a variable
emotions_numbers={}  # a dictionary created
i=0
for emo in unique_emotions:
    emotions_numbers[emo]=i
    i+=1

df['emotion']=df['emotion'].map(emotions_numbers)

df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

* now i wil do text cleaning

In [6]:
# lowercasing
df['text']=df['text'].apply(lambda x: x.lower())
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
# remove punctuations
import string # to use that function
# create a function to remove
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

df['text']=df['text'].apply(remove_punc)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
# removing numbers

# create a function to remove
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new

df['text']=df['text'].apply(remove_numbers)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [9]:
# remove emojis

'''
we will use ascii values
'''

def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new =new+i
  return new
df['text']=df['text'].apply(remove_emojis)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

* remove stop words; we will use a library using NLTK: natural language toolkit

In [10]:
'''
data with messages is called corpus: very large data collection
each individual word is called token'''


import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('punkt') # used to tokenize
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to C:\Users\Suryansh
[nltk_data]     Singh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Suryansh
[nltk_data]     Singh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [11]:
# first identify the stopwords
stopwords=set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [12]:
df.loc(1)['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [13]:
# convert the list of all words of text into an array and check if it exist in stop word and then remove if it does
def remove(txt):
  words=txt.split()
  cleaned=[]
  for i in words:
    if i not in stopwords:
      cleaned.append(i)

  return ' '.join(cleaned)

df['text']=df['text'].apply(remove)
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [14]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

# **THIS SECTION STARTS: NOT RELATED TO ABOVE**

# Bag of words

In [15]:
from re import X
# import the count vectorizer for tokenization and bag of words process
from sklearn.feature_extraction.text import CountVectorizer

# this will be our corpuss
documents=[
    "i love pizza",
    "pizza is the best",
    "i love pasta",
    "pasta is great"
]

# this is for create the vocabulary
vectorizer=CountVectorizer()
# send the documents to the fit into vecotorizar for futher process
X=vectorizer.fit_transform(documents)


print("vocabulary: ", vectorizer.get_feature_names_out())
print("\nbow matrix\n", X.toarray())

vocabulary:  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

bow matrix
 [[0 0 0 1 0 1 0]
 [1 0 1 0 0 1 1]
 [0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0]]

# example of n grams

In [16]:
from re import X
# import the count vectorizer for tokenization and bag of words process
from sklearn.feature_extraction.text import CountVectorizer

# this will be our corpuss
documents=[
    "i love pizza",
    "pizza is the best",
    "i love pasta",
    "pasta is great"
]

# this is for create the vocabulary
vectorizer=CountVectorizer(ngram_range=(2,2))
# send the documents to the fit into vecotorizar for futher process
X=vectorizer.fit_transform(documents)


print("vocabulary: ", vectorizer.get_feature_names_out())
print("\nbow matrix\n", X.toarray())

vocabulary:  ['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']

bow matrix
 [[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]

In [17]:
from re import X
# import the count vectorizer for tokenization and bag of words process
from sklearn.feature_extraction.text import CountVectorizer

# this will be our corpuss
documents=[
    "i love pizza",
    "pizza is the best",
    "i love pasta",
    "pasta is great"
]

# this is for create the vocabulary
vectorizer=CountVectorizer(ngram_range=(1,2))
# send the documents to the fit into vecotorizar for futher process
X=vectorizer.fit_transform(documents)


print("vocabulary: ", vectorizer.get_feature_names_out())
print("\nbow matrix\n", X.toarray())

vocabulary:  ['best' 'great' 'is' 'is great' 'is the' 'love' 'love pasta' 'love pizza'
 'pasta' 'pasta is' 'pizza' 'pizza is' 'the' 'the best']

bow matrix
 [[0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 1 0 0 0 0]]

# TF-IDF VECOTORIZER

In [18]:
# import tf-idf vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# this will be our corpuss
documents=[
    "i love pizza",
    "pizza is the best",
    "i love pasta",
    "pasta is great"
]

# this is for create the vocabulary
vectorizer=TfidfVectorizer()
# send the documents to the fit into vecotorizar for futher process
X=vectorizer.fit_transform(documents)


print("vocabulary: ", vectorizer.get_feature_names_out())
print("\nbow matrix\n", X.toarray())

vocabulary:  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

bow matrix
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]

# **THIS PART ENDS HERE: THIS IS NOT RELATED TO BELOW**

*  FROM our main project, we had removed the stop words from our table  
* now we have to split the text into 20:80 format

In [19]:
# for that we will do train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

NOW WE HAVE TO DO MODEL CREATION BUT BEFORE THAT WE HVAE TO **DO TEXT VECTORIZATION**

* our text is into => x train and x test-->> so i have to convert this into vectors, i will use both bag of words as well as tf-idf
* our emotion is into => y train and y test-->>so i have to convert this into vectors, i will use both bag of words as well as tf-idf

In [20]:
# imort CountVectorizer for bag of words, TfidfVectorizer for tf-idf
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

* 1. *bag of words*

In [21]:
# vectorizer for CountVectorizer(bag of words) to  create the vocabulary
bow_vectorizer=CountVectorizer()
# send the x train data to the do the text vectorization|
X_train_bow=bow_vectorizer.fit_transform(X_train)

# TRANSFORM test data using SAME vocabulary (NO fit!)
X_test_bow = bow_vectorizer.transform(X_test)  # ⚠️ Use .transform(), NOT .fit_transform();	ALWAYS on test/validation data (uses learned vocabulary)

In [22]:
# now create the model for bag of words-> i am using here naive bais model
from sklearn.naive_bayes import MultinomialNB # this naive bayes model is used for text classification
# to check the accuracy
from sklearn.metrics import accuracy_score
# initialize the model and create it
nb_model = MultinomialNB()
# send the data to the model to train it
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [23]:
# predict the testing data
pred_bow = nb_model.predict(X_test_bow)
# check the accuraacy score on testing y and predcitciton
print(accuracy_score(y_test, pred_bow))
print(pred_bow)

0.768125
[0 5 0 ... 5 5 0]

* 2. *tf-idf vectorizer*

In [24]:
# ============================================
# 1. TF-IDF Vectorization
# ============================================

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# FIT on training data (learn vocabulary and IDF values)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# TRANSFORM test data using SAME vocabulary (NO fit!)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# ============================================
# 2. Train Naive Bayes Model
# ============================================

# Create and train model
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [25]:
# ============================================
# 3. Predict and Evaluate
# ============================================

# Predict on test data
pred_tfidf = nb2_model.predict(X_test_tfidf)

# Accuracy Score
print(f"\nAccuracy: {accuracy_score(y_test, pred_tfidf)}")

Accuracy: 0.6609375

* 3. tf idf using logistci model also

In [26]:
# ============================================
# LOGISTIC REGRESSION WITH EVALUATION
# ============================================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)

# Train model
logistic_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [27]:
# Predict on test data
log_pred = logistic_model.predict(X_test_tfidf)

In [28]:
# Calculate and display accuracy
accuracy = accuracy_score(y_test, log_pred)
print(f"🎯 Logistic Regression Accuracy: {accuracy}")

🎯 Logistic Regression Accuracy: 0.8628125

In [30]:
# ============================================
# SAVE BEST MODEL FOR STREAMLIT APP
# ============================================

import joblib

# Find which model performed best
print("\n📊 Model Performance Summary:")
print(f"BOW + Naive Bayes: {accuracy_score(y_test, pred_bow):.4f}")
print(f"TF-IDF + Naive Bayes: {accuracy_score(y_test, pred_tfidf):.4f}")
print(f"TF-IDF + Logistic Regression: {accuracy_score(y_test, log_pred):.4f}")

# Choose the best model (TF-IDF + Logistic Regression usually works best)
best_model = logistic_model  # Or nb2_model, or nb_model
best_vectorizer = tfidf_vectorizer  # Or bow_vectorizer

# Save all files needed for Streamlit
joblib.dump(best_model, 'best_model.pkl')
joblib.dump(best_vectorizer, 'vectorizer.pkl')
joblib.dump(emotions_numbers, 'emotion_mapping.pkl')

print("\n✅ Models saved successfully!")

📊 Model Performance Summary:
BOW + Naive Bayes: 0.7681
TF-IDF + Naive Bayes: 0.6609
TF-IDF + Logistic Regression: 0.8628

✅ Models saved successfully!